#!/bin/bash
PREFIX="$HOME/.local";
SCRP_DIR=$(dirname "${BASH_SOURCE[0]}")
install_gpgman(){
	mkdir -p ${PREFIX}/bin
	mkdir -p ${PREFIX}/lib
	mkdir -p ${PREFIX}/share/bash-completion/completions
	chmod 755 ${PREFIX}/bin/*
	cp -f $SCRP_DIR/bin/* ${PREFIX}/bin
}
remove_gpgman(){
	rm -f ${PREFIX}/bin/gpgman\
	      ${PREFIX}/bin/awkeygrip\
	      ${PREFIX}/bin/secawk
}
if [ "$1" = "setup" ]; then
	install_gpgman;
	rm -r $HOME/gpgman;
	rm -r $HOME/Downloads/gpgman.zip;
fi
